#!/bin/sh

# setup database
rake db:create
rake db:migrate

# install all plugins to rails
for LINE in `rails g | grep install`
do
    rails g $LINE
done

# setup simple_form
rails g simple_form:install --bootstrap

# setup twitter bootstrap
rails g bootstrap:layout

# setup testing
bundle exec spork rspec --bootstrap
bundle exec spork cucumber --bootstrap

# setup guard
bundle exec guard init
